#set (PGPLOT_LIBRARIES "/usr/lib/libpgplot.so.5")
#set (GSL_LIBRARIES "$ENV{GSL_ROOT}/lib/libgsl.so")
#set (SCALAPACK_LIBRARIES "$ENV{SCALAPACK_ROOT}/lib/libscalapack.so")
#set (BLACS_LIBRARIES "/usr/lib/x86_64-linux-gnu/libblacs-openmpi.so")
set (FFTW_LIBRARIES "$ENV{FFTW_ROOT}/lib/libfftw3.so")
#set (BLAS_LIBRARIES "$ENV{BLAS_ROOT}/lib/libopenblas.so")
set(SCALAPACK_LIBRARIES "-L$ENV{MKLROOT}/lib/ -Wl,--start-group -lmkl_intel_lp64 -lmkl_sequential -lmkl_core -lmkl_blacs_intelmpi_lp64 -Wl,--end-group -lgomp -lpthread -lmkl_scalapack_lp64 -lm -ldl")
#set (LAPACK_LIBRARIES "/usr/lib/x86_64-linux-gnu/liblapack.so")
